### PR TITLE
feature: Add possibility to run multiple iterations of Lighthouse audits (#35)

### PR DESCRIPTION
**Pull request by tengremlin**

### CODE REVIEW

**Comment by soulgalore** [comment]
I didn't get around to look at this this weekend, sorry, I needed to push through [the coming filmstrip functionality in Compare](https://github.com/sitespeedio/compare/pull/95). @beenanner do you have any time the coming week to have a look?

**Comment by yurytomilin** [comment]
@tengremlin hi!
Is there any way we can help? Would be awesome to have this feature merged!
Thanks! :)

**Comment by soulgalore** [comment]
I'm travelling tomorrow and can maybe try it out then. But I'm a little reluctant since again at CDS there was some talk about that they will implement multiple runs in the future, but maybe we can fix so nothing needs to be fixed on our side at that time.

**Comment by soulgalore** [comment]
@tengremlin sorry for being so slow on this one. Yes looks good. I would have preferred having the Lighthouse result inside of the sitespeed.io HTML as before but I guess its hard to fix. I'll merge ASAP and it will go  out in the next release, probably next Friday.

**Comment by soulgalore** [comment]
thank you @tengremlin !

**Comment by soulgalore** [comment]
Hi @tengremlin any chance you have time to look at the https://github.com/sitespeedio/plugin-lighthouse/issues/42 that introduced with this PR? The thing that now it fires away Lighthouse tests directly when the URL arrives, making us run multiple Lighthouse tests at the same time if you test multiple URLs.

**Comment by soulgalore** [comment]
FYI: I've fixed it for now.

**Pull request merged**
